/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps without vendor
* lock-in.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Northstar, at https://www.jitblox.com/project/kxYI0irslt/northstar
*/

import { CommonModule } from '@angular/common';
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-contacts',
  host: { 'class': 'jbx-component' },
  templateUrl: './contacts.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [RouterLink, CommonModule]
})
export class ContactsComponent {

  constructor() {}
}
