/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps without vendor
* lock-in.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Northstar co, at null
*/

import { CommonModule } from '@angular/common';
import { Component, ViewChild } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NgbCollapse, NgbCollapseModule } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-root',
  host: { 'class': 'jbx-root' },
  styleUrls: ['./app.component.css'],
  templateUrl: './app.component.html',
  imports: [RouterLink, NgbCollapseModule, CommonModule]
})
export class AppComponent {
  @ViewChild('collapseNavbarNav') protected collapseNavbarNav!: NgbCollapse;

  constructor() {}

  protected onButton1Click($event: MouseEvent): void {
    this.collapseNavbarNav.toggle();
    $event.preventDefault();
  }

  protected onButton2Click($event: MouseEvent): void {
    alert('Cart opened');
    $event.preventDefault();
  }

  protected onButton4Click($event: MouseEvent): void {
    alert('Shopping cart opened');
    $event.preventDefault();
  }

  protected onDiv66Click($event: MouseEvent): void {
    alert('Viewing Statement Jackets category');
    $event.preventDefault();
  }

  protected onDiv70Click($event: MouseEvent): void {
    alert('Viewing Cashmere Sets category');
    $event.preventDefault();
  }

  protected onDiv74Click($event: MouseEvent): void {
    alert('Viewing Artisanal Crochetwear category');
    $event.preventDefault();
  }

  protected onDiv78Click($event: MouseEvent): void {
    alert('Viewing Accessories category');
    $event.preventDefault();
  }

  protected onHyperlink26Click($event: MouseEvent): void {
    alert('Contact information');
    $event.preventDefault();
  }

  protected onDiv153Click($event: MouseEvent): void {
    alert('Jackets category opened');
    $event.preventDefault();
  }

  protected onDiv157Click($event: MouseEvent): void {
    alert('Cashmere category opened');
    $event.preventDefault();
  }

  protected onDiv161Click($event: MouseEvent): void {
    alert('Crochetwear category opened');
    $event.preventDefault();
  }

  protected onDiv165Click($event: MouseEvent): void {
    alert('Accessories category opened');
    $event.preventDefault();
  }
}
