/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps without vendor
* lock-in.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Northstar, at https://www.jitblox.com/project/kxYI0irslt/northstar
*/

import { CommonModule } from '@angular/common';
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterLink } from '@angular/router';
import { UserProfileComponent } from './components/Components/user-profile.component';

@Component({
  selector: 'app-root',
  host: { 'class': 'jbx-root' },
  styleUrls: ['./app.component.css'],
  templateUrl: './app.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [UserProfileComponent, RouterLink, CommonModule]
})
export class AppComponent {

  constructor() {}

  protected onButton5Click($event: MouseEvent): void {
    alert('AI Concierge Coming Soon');
    $event.preventDefault();
  }

  protected onButton6Click($event: MouseEvent): void {
    alert('Product Detail Page - Coming Soon');
    $event.preventDefault();
  }

  protected onButton7Click($event: MouseEvent): void {
    alert('Product Detail Page - Coming Soon');
    $event.preventDefault();
  }

  protected onButton8Click($event: MouseEvent): void {
    alert('Product Detail Page - Coming Soon');
    $event.preventDefault();
  }

  protected onButton9Click($event: MouseEvent): void {
    alert('Product Detail Page - Coming Soon');
    $event.preventDefault();
  }

  protected onButton10Click($event: MouseEvent): void {
    alert('Product Detail Page - Coming Soon');
    $event.preventDefault();
  }

  protected onButton11Click($event: MouseEvent): void {
    alert('Full Catalog - Coming Soon');
    $event.preventDefault();
  }

  protected onButton12Click($event: MouseEvent): void {
    alert('Chat Interface Coming Soon');
    $event.preventDefault();
  }
}
