/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps without vendor
* lock-in.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Northstar, at https://www.jitblox.com/project/H8pRwCIqwN/northstar
*/

import { Routes } from '@angular/router';

export const routes: Routes = [
];
