/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps without vendor
* lock-in.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Northstar, at https://www.jitblox.com/project/H8pRwCIqwN/northstar
*/

import { CommonModule } from '@angular/common';
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterLink } from '@angular/router';
import { AgendaComponent } from '../Components/agenda.component';
import { ContactsComponent } from '../Components/contacts.component';
import { InboxComponent } from '../Components/inbox.component';
import { TodoListComponent } from '../Components/todo-list.component';

@Component({
  selector: 'app-home',
  host: { 'class': 'jbx-component' },
  templateUrl: './home.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  imports: [InboxComponent, AgendaComponent, RouterLink, ContactsComponent, TodoListComponent, CommonModule]
})
export class HomeComponent {

  constructor() {}
}
