/**
* Generated by JitBlox - a visual web app builder that lets you build modern web apps without vendor
* lock-in.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Northstar, at https://www.jitblox.com/project/kxYI0irslt/northstar
*/

import { bootstrapApplication } from '@angular/platform-browser';
import { setBasePath } from '@shoelace-style/shoelace';
import { AppComponent } from './app/app.component';
import { appConfig } from './app/app.config';

setBasePath('/assets/shoelace');

bootstrapApplication(AppComponent, appConfig)
  .catch(err => console.error(err));
